version: '3'

services:

  psql-db:
    image: postgres:16.1
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=student
      - POSTGRES_DB=cars
    volumes:
      - //c/workspace/datarsbp:/var/lib/postgresql/cars
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    stdin_open: true
    tty: true
    ports:
      - '5433:5432'


  carsbe:
    container_name: carsbe
    build:
      context: ./car-dealer-be
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/cars
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=student
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  
  carsfe:
    container_name: carsfe
    build:
      context: ./car-dealer-fe
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"    
    depends_on:
       - carsbe


