spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/cars
        driverClassName: org.postgresql.Driver
        username: postgres
        password: student
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8080
